services:
  db:
    image: postgres:15-alpine
    container_name: election-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: election_db
      POSTGRES_USER: election_user
      POSTGRES_PASSWORD: election_pass
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: election-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
      - static_volume:/code/staticfiles
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://election_user:election_pass@db:5432/election_db
      - ALLOWED_HOSTS=backend,localhost,127.0.0.1
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: election-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:

networks:
  app-network:
    driver: bridge
