# Generated by Django 4.2.25 on 2025-10-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votertoken',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='votertoken',
            constraint=models.UniqueConstraint(fields=('email', 'election'), name='uniq_email_per_election'),
        ),
    ]
