# Generated by Django 4.2.25 on 2025-10-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_votertoken_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votertoken',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
