# Generated by Django 4.2.25 on 2025-10-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_votertoken_emailed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='candidate',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/'),
        ),
    ]
